targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O4
      drift_dev:
        options:
          databases:
            app_database: lib/db/app_database.dart
      swagger_dart_code_generator:
        options:
          input_folder: swaggers/
          output_folder: lib/generated/
          use_path_for_request_names: true
